# fly.toml app configuration file generated for templ-starter on 2024-01-26T11:13:03-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'templ-starter'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
