name: "🚀 Build and Deploy to Prod"
on:
    push:
        branches:
            - "main"
    workflow_dispatch:
jobs:
    build_deploy:
        name: "🚀 Build and Deploy to Prod"
        runs-on: ubuntu-latest
        environment:
            name: fly.io
            url: ${{ steps.deploy.outputs.url }}
        steps:
            - uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '^1.21.6'
            - name: Get templ
              run: go install github.com/a-h/templ/cmd/templ@latest
            - run: templ -v
            - name: Setup Flyctl
              uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Make Prod
              run: make prod
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            - name: Set fly.io deploymentURL
              id: deploy
              run: echo "url=$(flyctl status -a templ-starter --json | jq -r '.Hostname')" >> $GITHUB_OUTPUT
