name: "🚀 Build and Deploy to Prod"
on:
  push:
    branches:
        - "main"
  workflow_dispatch:
jobs:      
  test:
    name: "🧪 Test"
    runs-on: ubuntu-latest
    env:
      POSTGRES_CONNECTION_STRING: ${{ secrets.DEV_POSTGRES_CONNECTION_STRING }}
      SUPABASE_URL: ${{ secrets.DEV_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.DEV_SUPABASE_KEY }}
      PORT: ${{ secrets.PORT }}
      BASE_URL: ${{ secrets.DEV_BASE_URL }}
      DOMAIN: ${{ secrets.DEV_DOMAIN }}
      ENV: dev
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.21.6'
      - name: Get templ
        run: go install github.com/a-h/templ/cmd/templ@latest
      - run: templ -v
      - name: Create .env file from env vars
        run: |
          echo "POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}\nSUPABASE_URL=${SUPABASE_URL}\nSUPABASE_KEY=${SUPABASE_KEY}\nPORT=${PORT}\nBASE_URL=${BASE_URL}\nDOMAIN=${DOMAIN}" > .env
          cat .env    
      - name: Test
        run: make test
  deploy:
    name: "🚀 Deploy to Prod"
    runs-on: ubuntu-latest
    needs: test
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      POSTGRES_CONNECTION_STRING: ${{ secrets.PROD_POSTGRES_CONNECTION_STRING }}
      SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.PROD_SUPABASE_KEY }}
      PORT: ${{ secrets.PORT }}
      BASE_URL: ${{ secrets.PROD_BASE_URL }}
      DOMAIN: ${{ secrets.PROD_DOMAIN }}
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    environment:
      name: fly.io
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Make Prod
        run: make prod
      - name: Set fly.io deploymentURL
        id: deploy
        run: echo "url=https://$(flyctl status -a templ-starter --json | jq -r '.Hostname')" >> $GITHUB_OUTPUT
