name: "🚀 Build and Deploy to Prod"
on:
    push:
        branches:
            - "main"
    workflow_dispatch:
jobs:
    build_deploy:
        name: "🚀 Build and Deploy to Prod"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                go-version: '^1.21.6'
            - name: Setup Flyctl
              uses: superfly/flyctl-actions/setup-flyctl@master

            - name: Make Prod
              run: make prod
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
